Moria E-W 1 Column Resets to West for Next Column
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		CUSTOM_CTRL_R
	End of group
End of macro
