Residential - Expanded Channel Style Mapping
		OPTION8
		CUSTOM_H
		A_STATUS_HEALTH
		A_TRAVEL_HIDE_INSTRUCTIONS
		SETUP_LOCAL_X_MDOWN
		BUILDJOB_TABLE_HALL
		HOTKEY_BUILDING_BOX
		HOTKEY_BUILDING_MACHINE_AXLE_HORIZONTAL
		HOTKEY_BUILDING_WORKSHOP_FISHERY
		BUILDING_DIM_X_DOWN
		BUILDING_TRIGGER_MAX_TRACK_CART_UP
		HOTKEY_GLASS_BOX
		HOTKEY_CARPENTER_BOX
		HOTKEY_CRAFTS_CLOTH
		HOTKEY_MASON_BOX
		HOTKEY_TRAP_HATCH
		STOCKPILE_CLOTH
		CIVZONE_HOSPITAL
		STORES_HIDE
		ANIMAL_HUNTING_TRAINING
		ORDERS_REFUSE_DUMP_STRAND_TISSUE
		ORDERS_ALL_HARVEST
		D_HAULING
		D_BITEM_HIDE
		D_LOOK_HIDE
		DESIGNATE_HIDE
		DESIGNATE_TRAFFIC_HIGH
		DESIGNATE_CHANNEL
		ITEM_HIDE
		UNITVIEW_HEALTH
		STRING_A104
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		SEC_SELECT
		SELECT_ALL
		D_MILITARY_ALERTS_SET_RETAIN
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		CUSTOM_X
		LEGENDS_EXPORT_XML
		A_ACTION
		HOTKEY_BUILDING_FLOODGATE
		HOTKEY_BUILDING_CONSTRUCTION_STAIR_UPDOWN
		BUILDING_ORIENT_DOWN
		BUILDING_EXPAND_CONTRACT
		BUILDING_TRIGGER_MAX_WATER_UP
		DESTROYBUILDING
		STOCKPILE_NONE
		CIVZONE_REMOVE
		ORDERS_EXCEPTIONS
		D_HAULING_REMOVE
		D_HAULING_STOP_REMOVE
		DESIGNATE_UNDO
		UNITVIEW_PRF_REMOVE_FROM_SQUAD
		D_SQUAD_SCH_CANCEL_ORDER
		STRING_A120
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		OPTION8
		CUSTOM_H
		A_STATUS_HEALTH
		A_TRAVEL_HIDE_INSTRUCTIONS
		SETUP_LOCAL_X_MDOWN
		BUILDJOB_TABLE_HALL
		HOTKEY_BUILDING_BOX
		HOTKEY_BUILDING_MACHINE_AXLE_HORIZONTAL
		HOTKEY_BUILDING_WORKSHOP_FISHERY
		BUILDING_DIM_X_DOWN
		BUILDING_TRIGGER_MAX_TRACK_CART_UP
		HOTKEY_GLASS_BOX
		HOTKEY_CARPENTER_BOX
		HOTKEY_CRAFTS_CLOTH
		HOTKEY_MASON_BOX
		HOTKEY_TRAP_HATCH
		STOCKPILE_CLOTH
		CIVZONE_HOSPITAL
		STORES_HIDE
		ANIMAL_HUNTING_TRAINING
		ORDERS_REFUSE_DUMP_STRAND_TISSUE
		ORDERS_ALL_HARVEST
		D_HAULING
		D_BITEM_HIDE
		D_LOOK_HIDE
		DESIGNATE_HIDE
		DESIGNATE_TRAFFIC_HIGH
		DESIGNATE_CHANNEL
		ITEM_HIDE
		UNITVIEW_HEALTH
		STRING_A104
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		CUSTOM_CTRL_R
	End of group
End of macro
