Room - Huge Stockpile
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		CUSTOM_CTRL_R
	End of group
End of macro
