Zone - Spammer
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		A_MOVE_E
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		A_MOVE_E
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		A_MOVE_E
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		A_MOVE_E
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		A_MOVE_E
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		A_MOVE_E
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		A_MOVE_E
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		A_MOVE_E
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		A_MOVE_E
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		A_MOVE_E
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		A_MOVE_E
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		A_MOVE_E
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		A_MOVE_E
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		A_MOVE_E
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		A_MOVE_E
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		A_MOVE_E
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		A_MOVE_E
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		A_MOVE_E
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		A_MOVE_E
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		A_MOVE_E
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		A_MOVE_E
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		A_MOVE_E
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		A_MOVE_E
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		A_MOVE_E
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		A_MOVE_E
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		A_MOVE_E
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		A_MOVE_E
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		A_MOVE_E
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		A_MOVE_E
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		A_MOVE_E
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		A_MOVE_E
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		A_MOVE_E
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		A_MOVE_E
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		A_MOVE_E
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		A_MOVE_E
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		A_MOVE_E
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		A_MOVE_E
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		A_MOVE_E
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		A_MOVE_E
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		A_MOVE_E
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		A_MOVE_E
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		A_MOVE_E
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		A_MOVE_E
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		A_MOVE_E
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		A_MOVE_E
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		A_MOVE_E
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		A_MOVE_E
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		A_MOVE_E
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		A_MOVE_E
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		A_MOVE_E
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		A_MOVE_E
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		A_MOVE_E
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		A_MOVE_E
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		A_MOVE_E
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		A_MOVE_E
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		A_MOVE_E
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		A_MOVE_E
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		A_MOVE_E
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		CUSTOM_W
		A_SLEEP_WAIT
		WILD_ATTACK
		A_ACTION_WRITE
		ADV_CONSTRUCTION_START
		A_INV_WEAR
		BUILDJOB_TARGET_UP
		BUILDJOB_CAGE_WATER
		BUILDJOB_RACK_MAT_WOOD
		BUILDJOB_STAND_MAT_WOOD
		HOTKEY_BUILDING_WORKSHOP
		HOTKEY_BUILDING_MACHINE_WATER_WHEEL
		HOTKEY_BUILDING_TRAP_WEAPON
		HOTKEY_BUILDING_CONSTRUCTION_WALL
		HOTKEY_BUILDING_WORKSHOP_FARMER
		HOTKEY_BUILDING_FURNACE_WOOD
		BUILDING_ORIENT_UP
		BUILDING_TRIGGER_ENABLE_WATER
		BUILDING_ROLLERS_SPEED_UP
		HOTKEY_GLASS_WEAPONRACK
		HOTKEY_CARPENTER_WEAPONRACK
		HOTKEY_CLOTHES_MAT_PLANT
		HOTKEY_CRAFTS_MAT_WOOD
		HOTKEY_CRAFTS_SEL_WOOD
		HOTKEY_SMITH_WEAPON
		HOTKEY_LOOM_WEAVE_CLOTH
		HOTKEY_MASON_WEAPONRACK
		HOTKEY_TRAP_GRATE_WALL
		BUILDJOB_STOCKPILE_WHEELBARROW
		STOCKPILE_WOOD
		CIVZONE_WATER_SOURCE
		ANIMAL_WAR_TRAINING
		ORDERS_GATHER_WOOD
		ORDERS_COLLECT_WEB
		D_BURROWS
		D_BURROWS_WORKSHOP_LIMIT
		D_LOOK_ARENA_WATER
		ARENA_WEATHER
		MILITARY_WEAPON
		MANAGER_WAGES
		DESIGNATE_TRAFFIC_INCREASE_WEIGHT
		UNITVIEW_WND
		STRING_A119
	End of group
		OPTION7
		CUSTOM_G
		A_GROUND
		A_CHANGE_DREAM
		A_CHANGE_GENDER
		A_LOG_ENTITIES
		BUILDJOB_DEPOT_BRING
		BUILDJOB_ANIMALTRAP_BAIT_GEM
		HOTKEY_BUILDING_BRIDGE
		HOTKEY_BUILDING_MACHINE_GEAR_ASSEMBLY
		HOTKEY_BUILDING_FURNACE_GLASS
		HIVE_GATHER_PRODUCTS
		BUILDING_TRIGGER_MAX_TRACK_CART_DOWN
		HOTKEY_GLASS_ROUGH
		HOTKEY_CRAFTS_MAT_STONE
		HOTKEY_JEWELER_FINISHED
		HOTKEY_TRAP_GRATE_FLOOR
		BUILDJOB_STOCKPILE_GIVE_TO
		STOCKPILE_FINISHED
		CIVZONE_GATHER
		ORDERS_GATHER_BODIES
		UNITVIEW_GEN
		STRING_A103
	End of group
		OPTION14
		CUSTOM_N
		WORLD_PARAM_NAME_ENTER
		WORLD_PARAM_NULLIFY
		ADV_CONSTRUCTION_ZONE_NEW
		SETUP_NOTES
		SETUP_NOTES_TAKE_NOTES
		SETUPGAME_NEW
		BUILDJOB_NOW
		BUILDJOB_BED_NAME
		HOTKEY_BUILDING_COFFIN
		HOTKEY_BUILDING_WORKSHOP_TANNER
		HOTKEY_BUILDING_FURNACE_KILN_LAVA
		LOCATION_RENAME
		HOTKEY_CARPENTER_BIN
		HOTKEY_LEATHER_BOX
		HOTKEY_CLOTHES_CHAIN
		HOTKEY_CRAFTS_HORN
		HOTKEY_SMITH_METAL
		STOCKPILE_COINS
		CIVZONE_PEN
		D_HOTKEY_CHANGE_NAME
		D_NOBLES
		D_HAULING_NICKNAME
		D_HAULING_STOP_NEW_DEPART
		D_BURROWS_NAME
		D_NOTE_NAME
		D_NOTE_ROUTE_NAME
		ARENA_CREATURE_NEW_ITEM
		WORK_ORDER_CONDITION_ITEM_NUMBER
		DESIGNATE_TRAFFIC_NORMAL
		DESIGNATE_REMOVE_CONSTRUCTION
		UNITVIEW_PRF_NEW_SQUAD
		CUSTOMIZE_UNIT_NICKNAME
		IMAGE_CREATOR_NAME
		D_MILITARY_UNIFORMS
		D_SQUAD_SCH_MS_NAME
		STRING_A110
	End of group
		MOVIE_SAVE
		SAVE_BINDINGS
		OPTION19
		CUSTOM_S
		WORLD_PARAM_SEED_ENTER
		A_STATUS_ATT_SKILL
		A_SLEEP_SLEEP
		ADV_CONSTRUCTION_WORK_MENU
		A_MOVEMENT_SWIM
		A_SNEAK
		A_STANCE
		A_LOG_SITES
		SETUP_NOTES_ADOPT_SYMBOL
		SETUPGAME_SAVE_PROFILE
		BUILDJOB_SUSPEND
		BUILDJOB_TARGET_DOWN
		BUILDJOB_DOOR_INTERNAL
		BUILDJOB_FARM_SEASFERT
		BUILDJOB_RACKSTAND_DEFAULTS1
		HOTKEY_BUILDING_STATUE
		HOTKEY_BUILDING_MACHINE_SCREW_PUMP
		HOTKEY_BUILDING_TRAP_STONE
		HOTKEY_BUILDING_WORKSHOP_SIEGE
		HOTKEY_BUILDING_FURNACE_SMELTER
		BUILDING_ORIENT_NONE
		BUILDING_TRIGGER_MIN_WATER_UP
		BUILDING_TRACK_STOP_FRICTION_UP
		SUSPENDBUILDING
		HOTKEY_COLLECT_SAND
		HOTKEY_CLOTHES_MAT_SILK
		HOTKEY_CRAFTS_SEL_SHELL
		HOTKEY_CRAFTS_SHELL
		HOTKEY_LOOM_WEAVE_SILK
		HOTKEY_FARMER_SHEAR_CREATURE
		HOTKEY_TRAP_SUPPORT
		BUILDJOB_STOCKPILE_SETTINGS
		STOCKPILE_STONE
		CIVZONE_SAND_COLLECT
		CIVZONE_GATHER_OPTIONS_PICK_SHRUBS
		ORDERS_REFUSE_DUMP_SHELL
		ORDERS_GATHER_STONE
		ORDERS_SLAUGHTER
		D_SQUADS
		D_HAULING_NEW_STOP
		D_HAULING_STOP_NEW_LINK
		D_NOTE_ADOPT_SYMBOL
		ARENA_CREATURE_SIDE_DOWN
		ARENA_WEATHER_SNOW
		ASSIGNTRADE_STRING
		NOBLELIST_SETTINGS
		TRADE_SEIZE
		DESIGNATE_SMOOTH
		UNITVIEW_SLAUGHTER
		D_MILITARY_SCHEDULE
		D_SQUADS_SCHEDULE
		D_SQUAD_SCH_SLEEP
		STRING_A115
	End of group
		OPTION3
		CUSTOM_C
		WORLD_PARAM_COPY
		WORLD_PARAM_REJECT_CONTINUE
		WORLD_GEN_CONTINUE
		LEGENDS_TOGGLE_CIVSITE
		A_COMBAT_CHARGEDEF
		A_STATUS_WRESTLE
		A_ACTION_CREATE
		A_COMPANIONS
		A_CUST_NAME
		A_TRAVEL_CLOUDS
		A_LOG_ZOOM_CURRENT_LOCATION
		SETUP_NOTES_CHANGE_SYMBOL_SELECTION
		CHOOSE_NAME_CLEAR
		SETUPGAME_CUSTOMIZE_UNIT
		BUILDJOB_CANCEL
		BUILDJOB_COFFIN_CIV
		BUILDJOB_FARM_AUTUMN
		BUILDJOB_RACK_MAT_COPPER
		BUILDJOB_STAND_MAT_COPPER
		BUILDJOB_RACKSTAND_KILL1
		HOTKEY_BUILDING_CHAIR
		HOTKEY_BUILDING_SIEGEENGINE_CATAPULT
		HOTKEY_BUILDING_TRAP_CAGE
		HOTKEY_BUILDING_WORKSHOP_CARPENTER
		HIVE_INSTALL_COLONY
		BUILDING_TRIGGER_ENABLE_CREATURE
		HOTKEY_MAKE_CHARCOAL
		HOTKEY_GLASS_CLEAR
		HOTKEY_COLLECT_CLAY
		HOTKEY_CARPENTER_CHAIR
		HOTKEY_SIEGE_CATAPULT
		HOTKEY_CRAFTS_MAT_CRAFTS
		HOTKEY_LOOM_COLLECT_SILK
		HOTKEY_KITCHEN_COOK_4
		HOTKEY_FARMER_CHEESE
		HOTKEY_DYER_CLOTH
		HOTKEY_JEWELER_CUT
		HOTKEY_MASON_CHAIR
		HOTKEY_TRAP_CHAIN
		BUILDJOB_STOCKPILE_BIN_DOWN
		STOCKPILE_CUSTOM
		CIVZONE_CLAY_COLLECT
		KITCHEN_COOK
		ORDERS_FORBID_YOUR_CORPSE
		ORDERS_REFUSE_DUMP_CORPSE
		D_CIVLIST
		D_HAULING_STOP_LC_CHANGE
		D_BURROWS_ADD_UNIT
		D_BURROWS_CHANGE_SELECTION
		D_NOTE_CHANGE_SELECTION
		D_NOTE_ROUTE_CENTER
		D_LOOK_ARENA_CREATURE
		ARENA_CONFLICT_STATE_1
		NOBLELIST_CAPITAL
		MILITARY_ZOOM
		MANAGER_CONDITIONS
		WORK_ORDER_CONDITION_ORDER_ACTIVATION
		DESIGNATE_CLAIM
		UNITVIEW_GEN_COMBAT
		D_MILITARY_CREATE_SQUAD
		D_MILITARY_CANCEL_ORDERS
		D_MILITARY_ALERTS_ADD
		D_MILITARY_AMMUNITION_ADD_ITEM
		D_MILITARY_ADD_UNIFORM
		D_SQUAD_SCH_COPY_ORDERS
		STRING_A099
	End of group
		OPTION20
		CUSTOM_T
		WORLD_PARAM_TITLE
		WORLD_PARAM_REJECT_ALLOW_THIS
		A_THROW
		A_LOG_TASKS
		A_BARTER_TRADE
		BUILDJOB_BED_TRAIN
		BUILDJOB_DEPOT_TRADE
		HOTKEY_BUILDING_TABLE
		HOTKEY_BUILDING_WORKSHOP_MECHANIC
		BUILDING_TRIGGER_MIN_TRACK_CART_DOWN
		BUILDINGLIST_ZOOM_T
		LOCATION_TEMPLE
		HOTKEY_GLASS_TABLE
		HOTKEY_CARPENTER_TABLE
		HOTKEY_LEATHER_SHIRT
		HOTKEY_CLOTHES_SHIRT
		HOTKEY_CRAFTS_TOTEM
		HOTKEY_SMITH_TRAP
		HOTKEY_KENNEL_TAME_VERMIN
		HOTKEY_TANNER_TAN
		HOTKEY_DYER_THREAD
		HOTKEY_MECHANIC_PARTS
		HOTKEY_MASON_TABLE
		BUILDJOB_STOCKPILE_MASTER
		STOCKPILE_CUSTOM_SETTINGS
		CIVZONE_ANIMAL_TRAINING
		CIVZONE_GATHER_OPTIONS_PICK_TREES
		ANIMAL_SELECT_TRAINER
		ORDERS_FORBID_OTHER_ITEMS
		ORDERS_TAN
		D_HAULING_STOP_SL_TAKE_GIVE
		D_HAULING_STOP_LC_TIMER_DOWN
		D_NOTE_ENTER
		D_BUILDITEM
		D_LOOK_ARENA_TREE
		TRADE_TRADE
		MANAGER_MAX
		WORK_ORDER_CONDITION_ITEM_TRAITS
		DESIGNATE_CHOP
		D_MILITARY_TRAINING
		D_SQUADS_ALERT
		STRING_A116
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		CUSTOM_CTRL_R
	End of group
End of macro
