Jail - From NNW Cage
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		OPTION10
		CUSTOM_J
		A_JUMP
		BUILDJOB_CAGE_JUSTICE
		BUILDJOB_CHAIN_JUSTICE
		HOTKEY_BUILDING_CAGE
		HOTKEY_BUILDING_WORKSHOP_JEWELER
		BUILDING_TRIGGER_MAX_MAGMA_DOWN
		HOTKEY_GLASS_CAGE
		HOTKEY_CARPENTER_CAGE
		HOTKEY_TRAP_CAGE
		STOCKPILE_SETTINGS_SPECIFIC2
		D_JOBLIST
		DESIGNATE_STAIR_DOWN
		STRING_A106
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		OPTION10
		CUSTOM_J
		A_JUMP
		BUILDJOB_CAGE_JUSTICE
		BUILDJOB_CHAIN_JUSTICE
		HOTKEY_BUILDING_CAGE
		HOTKEY_BUILDING_WORKSHOP_JEWELER
		BUILDING_TRIGGER_MAX_MAGMA_DOWN
		HOTKEY_GLASS_CAGE
		HOTKEY_CARPENTER_CAGE
		HOTKEY_TRAP_CAGE
		STOCKPILE_SETTINGS_SPECIFIC2
		D_JOBLIST
		DESIGNATE_STAIR_DOWN
		STRING_A106
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		OPTION10
		CUSTOM_J
		A_JUMP
		BUILDJOB_CAGE_JUSTICE
		BUILDJOB_CHAIN_JUSTICE
		HOTKEY_BUILDING_CAGE
		HOTKEY_BUILDING_WORKSHOP_JEWELER
		BUILDING_TRIGGER_MAX_MAGMA_DOWN
		HOTKEY_GLASS_CAGE
		HOTKEY_CARPENTER_CAGE
		HOTKEY_TRAP_CAGE
		STOCKPILE_SETTINGS_SPECIFIC2
		D_JOBLIST
		DESIGNATE_STAIR_DOWN
		STRING_A106
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		OPTION10
		CUSTOM_J
		A_JUMP
		BUILDJOB_CAGE_JUSTICE
		BUILDJOB_CHAIN_JUSTICE
		HOTKEY_BUILDING_CAGE
		HOTKEY_BUILDING_WORKSHOP_JEWELER
		BUILDING_TRIGGER_MAX_MAGMA_DOWN
		HOTKEY_GLASS_CAGE
		HOTKEY_CARPENTER_CAGE
		HOTKEY_TRAP_CAGE
		STOCKPILE_SETTINGS_SPECIFIC2
		D_JOBLIST
		DESIGNATE_STAIR_DOWN
		STRING_A106
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		OPTION10
		CUSTOM_J
		A_JUMP
		BUILDJOB_CAGE_JUSTICE
		BUILDJOB_CHAIN_JUSTICE
		HOTKEY_BUILDING_CAGE
		HOTKEY_BUILDING_WORKSHOP_JEWELER
		BUILDING_TRIGGER_MAX_MAGMA_DOWN
		HOTKEY_GLASS_CAGE
		HOTKEY_CARPENTER_CAGE
		HOTKEY_TRAP_CAGE
		STOCKPILE_SETTINGS_SPECIFIC2
		D_JOBLIST
		DESIGNATE_STAIR_DOWN
		STRING_A106
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		OPTION10
		CUSTOM_J
		A_JUMP
		BUILDJOB_CAGE_JUSTICE
		BUILDJOB_CHAIN_JUSTICE
		HOTKEY_BUILDING_CAGE
		HOTKEY_BUILDING_WORKSHOP_JEWELER
		BUILDING_TRIGGER_MAX_MAGMA_DOWN
		HOTKEY_GLASS_CAGE
		HOTKEY_CARPENTER_CAGE
		HOTKEY_TRAP_CAGE
		STOCKPILE_SETTINGS_SPECIFIC2
		D_JOBLIST
		DESIGNATE_STAIR_DOWN
		STRING_A106
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		OPTION10
		CUSTOM_J
		A_JUMP
		BUILDJOB_CAGE_JUSTICE
		BUILDJOB_CHAIN_JUSTICE
		HOTKEY_BUILDING_CAGE
		HOTKEY_BUILDING_WORKSHOP_JEWELER
		BUILDING_TRIGGER_MAX_MAGMA_DOWN
		HOTKEY_GLASS_CAGE
		HOTKEY_CARPENTER_CAGE
		HOTKEY_TRAP_CAGE
		STOCKPILE_SETTINGS_SPECIFIC2
		D_JOBLIST
		DESIGNATE_STAIR_DOWN
		STRING_A106
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		OPTION10
		CUSTOM_J
		A_JUMP
		BUILDJOB_CAGE_JUSTICE
		BUILDJOB_CHAIN_JUSTICE
		HOTKEY_BUILDING_CAGE
		HOTKEY_BUILDING_WORKSHOP_JEWELER
		BUILDING_TRIGGER_MAX_MAGMA_DOWN
		HOTKEY_GLASS_CAGE
		HOTKEY_CARPENTER_CAGE
		HOTKEY_TRAP_CAGE
		STOCKPILE_SETTINGS_SPECIFIC2
		D_JOBLIST
		DESIGNATE_STAIR_DOWN
		STRING_A106
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		OPTION10
		CUSTOM_J
		A_JUMP
		BUILDJOB_CAGE_JUSTICE
		BUILDJOB_CHAIN_JUSTICE
		HOTKEY_BUILDING_CAGE
		HOTKEY_BUILDING_WORKSHOP_JEWELER
		BUILDING_TRIGGER_MAX_MAGMA_DOWN
		HOTKEY_GLASS_CAGE
		HOTKEY_CARPENTER_CAGE
		HOTKEY_TRAP_CAGE
		STOCKPILE_SETTINGS_SPECIFIC2
		D_JOBLIST
		DESIGNATE_STAIR_DOWN
		STRING_A106
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		OPTION10
		CUSTOM_J
		A_JUMP
		BUILDJOB_CAGE_JUSTICE
		BUILDJOB_CHAIN_JUSTICE
		HOTKEY_BUILDING_CAGE
		HOTKEY_BUILDING_WORKSHOP_JEWELER
		BUILDING_TRIGGER_MAX_MAGMA_DOWN
		HOTKEY_GLASS_CAGE
		HOTKEY_CARPENTER_CAGE
		HOTKEY_TRAP_CAGE
		STOCKPILE_SETTINGS_SPECIFIC2
		D_JOBLIST
		DESIGNATE_STAIR_DOWN
		STRING_A106
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		OPTION10
		CUSTOM_J
		A_JUMP
		BUILDJOB_CAGE_JUSTICE
		BUILDJOB_CHAIN_JUSTICE
		HOTKEY_BUILDING_CAGE
		HOTKEY_BUILDING_WORKSHOP_JEWELER
		BUILDING_TRIGGER_MAX_MAGMA_DOWN
		HOTKEY_GLASS_CAGE
		HOTKEY_CARPENTER_CAGE
		HOTKEY_TRAP_CAGE
		STOCKPILE_SETTINGS_SPECIFIC2
		D_JOBLIST
		DESIGNATE_STAIR_DOWN
		STRING_A106
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		OPTION10
		CUSTOM_J
		A_JUMP
		BUILDJOB_CAGE_JUSTICE
		BUILDJOB_CHAIN_JUSTICE
		HOTKEY_BUILDING_CAGE
		HOTKEY_BUILDING_WORKSHOP_JEWELER
		BUILDING_TRIGGER_MAX_MAGMA_DOWN
		HOTKEY_GLASS_CAGE
		HOTKEY_CARPENTER_CAGE
		HOTKEY_TRAP_CAGE
		STOCKPILE_SETTINGS_SPECIFIC2
		D_JOBLIST
		DESIGNATE_STAIR_DOWN
		STRING_A106
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		OPTION10
		CUSTOM_J
		A_JUMP
		BUILDJOB_CAGE_JUSTICE
		BUILDJOB_CHAIN_JUSTICE
		HOTKEY_BUILDING_CAGE
		HOTKEY_BUILDING_WORKSHOP_JEWELER
		BUILDING_TRIGGER_MAX_MAGMA_DOWN
		HOTKEY_GLASS_CAGE
		HOTKEY_CARPENTER_CAGE
		HOTKEY_TRAP_CAGE
		STOCKPILE_SETTINGS_SPECIFIC2
		D_JOBLIST
		DESIGNATE_STAIR_DOWN
		STRING_A106
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		OPTION4
		CUSTOM_D
		WORLD_PARAM_DELETE
		LEGENDS_EXPORT_DETAILED_MAP
		A_COMBAT_DODGE
		A_STATUS_DESC
		A_SLEEP_DAWN
		A_INV_DROP
		A_END_TRAVEL
		SETUP_NOTES_DELETE_NOTE
		BUILDJOB_TARGET_RIGHT
		BUILDJOB_BED_DORMITORY
		BUILDJOB_FARM_WINTER
		BUILDJOB_RACKSTAND_KILL2
		HOTKEY_BUILDING_DOOR
		HOTKEY_BUILDING_CONSTRUCTION_STAIR_DOWN
		HOTKEY_BUILDING_WORKSHOP_DYER
		BUILDING_ORIENT_RIGHT
		BUILDING_ADVANCE_STAGE
		BUILDING_TRIGGER_MAX_SIZE_DOWN
		BUILDING_TRACK_STOP_DUMP
		HOTKEY_GLASS_DOOR
		HOTKEY_CARPENTER_DOOR
		HOTKEY_MASON_DOOR
		HOTKEY_TRAP_DOOR
		BUILDJOB_STOCKPILE_DELETE_CHILD
		STOCKPILE_ARMOR
		STOCKPILE_SETTINGS_DISABLE
		STORES_DUMP
		ORDERS_DYED_CLOTH
		ORDERS_ZONE_DRINKING
		D_DESIGNATE
		D_HAULING_STOP_LC_DIR
		D_BURROWS_DELETE
		D_NOTE_DELETE
		D_NOTE_ROUTE_DELETE
		D_BITEM_DUMP
		D_LOOK_DUMP
		ARENA_CREATURE_SIDE_UP
		ASSIGNTRADE_SORT
		DESIGNATE_DUMP
		DESIGNATE_DIG
		ITEM_DUMP
		D_MILITARY_DISBAND_SQUAD
		D_MILITARY_ALERTS_DELETE
		D_MILITARY_AMMUNITION_REMOVE_ITEM
		D_MILITARY_DELETE_UNIFORM
		STRING_A100
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		OPTION4
		CUSTOM_D
		WORLD_PARAM_DELETE
		LEGENDS_EXPORT_DETAILED_MAP
		A_COMBAT_DODGE
		A_STATUS_DESC
		A_SLEEP_DAWN
		A_INV_DROP
		A_END_TRAVEL
		SETUP_NOTES_DELETE_NOTE
		BUILDJOB_TARGET_RIGHT
		BUILDJOB_BED_DORMITORY
		BUILDJOB_FARM_WINTER
		BUILDJOB_RACKSTAND_KILL2
		HOTKEY_BUILDING_DOOR
		HOTKEY_BUILDING_CONSTRUCTION_STAIR_DOWN
		HOTKEY_BUILDING_WORKSHOP_DYER
		BUILDING_ORIENT_RIGHT
		BUILDING_ADVANCE_STAGE
		BUILDING_TRIGGER_MAX_SIZE_DOWN
		BUILDING_TRACK_STOP_DUMP
		HOTKEY_GLASS_DOOR
		HOTKEY_CARPENTER_DOOR
		HOTKEY_MASON_DOOR
		HOTKEY_TRAP_DOOR
		BUILDJOB_STOCKPILE_DELETE_CHILD
		STOCKPILE_ARMOR
		STOCKPILE_SETTINGS_DISABLE
		STORES_DUMP
		ORDERS_DYED_CLOTH
		ORDERS_ZONE_DRINKING
		D_DESIGNATE
		D_HAULING_STOP_LC_DIR
		D_BURROWS_DELETE
		D_NOTE_DELETE
		D_NOTE_ROUTE_DELETE
		D_BITEM_DUMP
		D_LOOK_DUMP
		ARENA_CREATURE_SIDE_UP
		ASSIGNTRADE_SORT
		DESIGNATE_DUMP
		DESIGNATE_DIG
		ITEM_DUMP
		D_MILITARY_DISBAND_SQUAD
		D_MILITARY_ALERTS_DELETE
		D_MILITARY_AMMUNITION_REMOVE_ITEM
		D_MILITARY_DELETE_UNIFORM
		STRING_A100
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		OPTION10
		CUSTOM_J
		A_JUMP
		BUILDJOB_CAGE_JUSTICE
		BUILDJOB_CHAIN_JUSTICE
		HOTKEY_BUILDING_CAGE
		HOTKEY_BUILDING_WORKSHOP_JEWELER
		BUILDING_TRIGGER_MAX_MAGMA_DOWN
		HOTKEY_GLASS_CAGE
		HOTKEY_CARPENTER_CAGE
		HOTKEY_TRAP_CAGE
		STOCKPILE_SETTINGS_SPECIFIC2
		D_JOBLIST
		DESIGNATE_STAIR_DOWN
		STRING_A106
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		OPTION10
		CUSTOM_J
		A_JUMP
		BUILDJOB_CAGE_JUSTICE
		BUILDJOB_CHAIN_JUSTICE
		HOTKEY_BUILDING_CAGE
		HOTKEY_BUILDING_WORKSHOP_JEWELER
		BUILDING_TRIGGER_MAX_MAGMA_DOWN
		HOTKEY_GLASS_CAGE
		HOTKEY_CARPENTER_CAGE
		HOTKEY_TRAP_CAGE
		STOCKPILE_SETTINGS_SPECIFIC2
		D_JOBLIST
		DESIGNATE_STAIR_DOWN
		STRING_A106
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		OPTION10
		CUSTOM_J
		A_JUMP
		BUILDJOB_CAGE_JUSTICE
		BUILDJOB_CHAIN_JUSTICE
		HOTKEY_BUILDING_CAGE
		HOTKEY_BUILDING_WORKSHOP_JEWELER
		BUILDING_TRIGGER_MAX_MAGMA_DOWN
		HOTKEY_GLASS_CAGE
		HOTKEY_CARPENTER_CAGE
		HOTKEY_TRAP_CAGE
		STOCKPILE_SETTINGS_SPECIFIC2
		D_JOBLIST
		DESIGNATE_STAIR_DOWN
		STRING_A106
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		OPTION10
		CUSTOM_J
		A_JUMP
		BUILDJOB_CAGE_JUSTICE
		BUILDJOB_CHAIN_JUSTICE
		HOTKEY_BUILDING_CAGE
		HOTKEY_BUILDING_WORKSHOP_JEWELER
		BUILDING_TRIGGER_MAX_MAGMA_DOWN
		HOTKEY_GLASS_CAGE
		HOTKEY_CARPENTER_CAGE
		HOTKEY_TRAP_CAGE
		STOCKPILE_SETTINGS_SPECIFIC2
		D_JOBLIST
		DESIGNATE_STAIR_DOWN
		STRING_A106
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		OPTION10
		CUSTOM_J
		A_JUMP
		BUILDJOB_CAGE_JUSTICE
		BUILDJOB_CHAIN_JUSTICE
		HOTKEY_BUILDING_CAGE
		HOTKEY_BUILDING_WORKSHOP_JEWELER
		BUILDING_TRIGGER_MAX_MAGMA_DOWN
		HOTKEY_GLASS_CAGE
		HOTKEY_CARPENTER_CAGE
		HOTKEY_TRAP_CAGE
		STOCKPILE_SETTINGS_SPECIFIC2
		D_JOBLIST
		DESIGNATE_STAIR_DOWN
		STRING_A106
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		OPTION10
		CUSTOM_J
		A_JUMP
		BUILDJOB_CAGE_JUSTICE
		BUILDJOB_CHAIN_JUSTICE
		HOTKEY_BUILDING_CAGE
		HOTKEY_BUILDING_WORKSHOP_JEWELER
		BUILDING_TRIGGER_MAX_MAGMA_DOWN
		HOTKEY_GLASS_CAGE
		HOTKEY_CARPENTER_CAGE
		HOTKEY_TRAP_CAGE
		STOCKPILE_SETTINGS_SPECIFIC2
		D_JOBLIST
		DESIGNATE_STAIR_DOWN
		STRING_A106
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		CUSTOM_V
		HEAVY_ATTACK
		A_CENTER
		A_BARTER_VIEW
		SETUPGAME_VIEW
		HOTKEY_BUILDING_CHAIN
		HOTKEY_BUILDING_MACHINE_AXLE_VERTICAL
		HOTKEY_BUILDING_WORKSHOP_LAVAMILL
		BUILDING_VIEW_ITEM
		HOTKEY_CARPENTER_BARREL
		HOTKEY_LEATHER_QUIVER
		HOTKEY_FARMER_PROCESS_VIAL
		BUILDJOB_STOCKPILE_BIN_UP
		CIVZONE_NEXT
		STORES_VIEW
		ORDERS_REFUSE_OUTSIDE_VERMIN
		D_VIEWUNIT
		D_HAULING_VEHICLE
		ASSIGNTRADE_VIEW
		NOBLELIST_VIEW_CANDIDATE
		TRADE_VIEW
		MILITARY_VIEW
		UNITJOB_VIEW
		DESIGNATE_TOGGLE_ENGRAVING
		ITEM_DESCRIPTION
		UNITVIEW_RELATIONSHIPS_VIEW
		UNITVIEW_NEXT
		STRING_A118
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		CUSTOM_V
		HEAVY_ATTACK
		A_CENTER
		A_BARTER_VIEW
		SETUPGAME_VIEW
		HOTKEY_BUILDING_CHAIN
		HOTKEY_BUILDING_MACHINE_AXLE_VERTICAL
		HOTKEY_BUILDING_WORKSHOP_LAVAMILL
		BUILDING_VIEW_ITEM
		HOTKEY_CARPENTER_BARREL
		HOTKEY_LEATHER_QUIVER
		HOTKEY_FARMER_PROCESS_VIAL
		BUILDJOB_STOCKPILE_BIN_UP
		CIVZONE_NEXT
		STORES_VIEW
		ORDERS_REFUSE_OUTSIDE_VERMIN
		D_VIEWUNIT
		D_HAULING_VEHICLE
		ASSIGNTRADE_VIEW
		NOBLELIST_VIEW_CANDIDATE
		TRADE_VIEW
		MILITARY_VIEW
		UNITJOB_VIEW
		DESIGNATE_TOGGLE_ENGRAVING
		ITEM_DESCRIPTION
		UNITVIEW_RELATIONSHIPS_VIEW
		UNITVIEW_NEXT
		STRING_A118
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		CUSTOM_V
		HEAVY_ATTACK
		A_CENTER
		A_BARTER_VIEW
		SETUPGAME_VIEW
		HOTKEY_BUILDING_CHAIN
		HOTKEY_BUILDING_MACHINE_AXLE_VERTICAL
		HOTKEY_BUILDING_WORKSHOP_LAVAMILL
		BUILDING_VIEW_ITEM
		HOTKEY_CARPENTER_BARREL
		HOTKEY_LEATHER_QUIVER
		HOTKEY_FARMER_PROCESS_VIAL
		BUILDJOB_STOCKPILE_BIN_UP
		CIVZONE_NEXT
		STORES_VIEW
		ORDERS_REFUSE_OUTSIDE_VERMIN
		D_VIEWUNIT
		D_HAULING_VEHICLE
		ASSIGNTRADE_VIEW
		NOBLELIST_VIEW_CANDIDATE
		TRADE_VIEW
		MILITARY_VIEW
		UNITJOB_VIEW
		DESIGNATE_TOGGLE_ENGRAVING
		ITEM_DESCRIPTION
		UNITVIEW_RELATIONSHIPS_VIEW
		UNITVIEW_NEXT
		STRING_A118
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		CUSTOM_V
		HEAVY_ATTACK
		A_CENTER
		A_BARTER_VIEW
		SETUPGAME_VIEW
		HOTKEY_BUILDING_CHAIN
		HOTKEY_BUILDING_MACHINE_AXLE_VERTICAL
		HOTKEY_BUILDING_WORKSHOP_LAVAMILL
		BUILDING_VIEW_ITEM
		HOTKEY_CARPENTER_BARREL
		HOTKEY_LEATHER_QUIVER
		HOTKEY_FARMER_PROCESS_VIAL
		BUILDJOB_STOCKPILE_BIN_UP
		CIVZONE_NEXT
		STORES_VIEW
		ORDERS_REFUSE_OUTSIDE_VERMIN
		D_VIEWUNIT
		D_HAULING_VEHICLE
		ASSIGNTRADE_VIEW
		NOBLELIST_VIEW_CANDIDATE
		TRADE_VIEW
		MILITARY_VIEW
		UNITJOB_VIEW
		DESIGNATE_TOGGLE_ENGRAVING
		ITEM_DESCRIPTION
		UNITVIEW_RELATIONSHIPS_VIEW
		UNITVIEW_NEXT
		STRING_A118
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		CUSTOM_V
		HEAVY_ATTACK
		A_CENTER
		A_BARTER_VIEW
		SETUPGAME_VIEW
		HOTKEY_BUILDING_CHAIN
		HOTKEY_BUILDING_MACHINE_AXLE_VERTICAL
		HOTKEY_BUILDING_WORKSHOP_LAVAMILL
		BUILDING_VIEW_ITEM
		HOTKEY_CARPENTER_BARREL
		HOTKEY_LEATHER_QUIVER
		HOTKEY_FARMER_PROCESS_VIAL
		BUILDJOB_STOCKPILE_BIN_UP
		CIVZONE_NEXT
		STORES_VIEW
		ORDERS_REFUSE_OUTSIDE_VERMIN
		D_VIEWUNIT
		D_HAULING_VEHICLE
		ASSIGNTRADE_VIEW
		NOBLELIST_VIEW_CANDIDATE
		TRADE_VIEW
		MILITARY_VIEW
		UNITJOB_VIEW
		DESIGNATE_TOGGLE_ENGRAVING
		ITEM_DESCRIPTION
		UNITVIEW_RELATIONSHIPS_VIEW
		UNITVIEW_NEXT
		STRING_A118
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		CUSTOM_V
		HEAVY_ATTACK
		A_CENTER
		A_BARTER_VIEW
		SETUPGAME_VIEW
		HOTKEY_BUILDING_CHAIN
		HOTKEY_BUILDING_MACHINE_AXLE_VERTICAL
		HOTKEY_BUILDING_WORKSHOP_LAVAMILL
		BUILDING_VIEW_ITEM
		HOTKEY_CARPENTER_BARREL
		HOTKEY_LEATHER_QUIVER
		HOTKEY_FARMER_PROCESS_VIAL
		BUILDJOB_STOCKPILE_BIN_UP
		CIVZONE_NEXT
		STORES_VIEW
		ORDERS_REFUSE_OUTSIDE_VERMIN
		D_VIEWUNIT
		D_HAULING_VEHICLE
		ASSIGNTRADE_VIEW
		NOBLELIST_VIEW_CANDIDATE
		TRADE_VIEW
		MILITARY_VIEW
		UNITJOB_VIEW
		DESIGNATE_TOGGLE_ENGRAVING
		ITEM_DESCRIPTION
		UNITVIEW_RELATIONSHIPS_VIEW
		UNITVIEW_NEXT
		STRING_A118
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		STANDARDSCROLL_UP
		CURSOR_UP
		A_MOVE_N
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		OPTION4
		CUSTOM_D
		WORLD_PARAM_DELETE
		LEGENDS_EXPORT_DETAILED_MAP
		A_COMBAT_DODGE
		A_STATUS_DESC
		A_SLEEP_DAWN
		A_INV_DROP
		A_END_TRAVEL
		SETUP_NOTES_DELETE_NOTE
		BUILDJOB_TARGET_RIGHT
		BUILDJOB_BED_DORMITORY
		BUILDJOB_FARM_WINTER
		BUILDJOB_RACKSTAND_KILL2
		HOTKEY_BUILDING_DOOR
		HOTKEY_BUILDING_CONSTRUCTION_STAIR_DOWN
		HOTKEY_BUILDING_WORKSHOP_DYER
		BUILDING_ORIENT_RIGHT
		BUILDING_ADVANCE_STAGE
		BUILDING_TRIGGER_MAX_SIZE_DOWN
		BUILDING_TRACK_STOP_DUMP
		HOTKEY_GLASS_DOOR
		HOTKEY_CARPENTER_DOOR
		HOTKEY_MASON_DOOR
		HOTKEY_TRAP_DOOR
		BUILDJOB_STOCKPILE_DELETE_CHILD
		STOCKPILE_ARMOR
		STOCKPILE_SETTINGS_DISABLE
		STORES_DUMP
		ORDERS_DYED_CLOTH
		ORDERS_ZONE_DRINKING
		D_DESIGNATE
		D_HAULING_STOP_LC_DIR
		D_BURROWS_DELETE
		D_NOTE_DELETE
		D_NOTE_ROUTE_DELETE
		D_BITEM_DUMP
		D_LOOK_DUMP
		ARENA_CREATURE_SIDE_UP
		ASSIGNTRADE_SORT
		DESIGNATE_DUMP
		DESIGNATE_DIG
		ITEM_DUMP
		D_MILITARY_DISBAND_SQUAD
		D_MILITARY_ALERTS_DELETE
		D_MILITARY_AMMUNITION_REMOVE_ITEM
		D_MILITARY_DELETE_UNIFORM
		STRING_A100
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		OPTION4
		CUSTOM_D
		WORLD_PARAM_DELETE
		LEGENDS_EXPORT_DETAILED_MAP
		A_COMBAT_DODGE
		A_STATUS_DESC
		A_SLEEP_DAWN
		A_INV_DROP
		A_END_TRAVEL
		SETUP_NOTES_DELETE_NOTE
		BUILDJOB_TARGET_RIGHT
		BUILDJOB_BED_DORMITORY
		BUILDJOB_FARM_WINTER
		BUILDJOB_RACKSTAND_KILL2
		HOTKEY_BUILDING_DOOR
		HOTKEY_BUILDING_CONSTRUCTION_STAIR_DOWN
		HOTKEY_BUILDING_WORKSHOP_DYER
		BUILDING_ORIENT_RIGHT
		BUILDING_ADVANCE_STAGE
		BUILDING_TRIGGER_MAX_SIZE_DOWN
		BUILDING_TRACK_STOP_DUMP
		HOTKEY_GLASS_DOOR
		HOTKEY_CARPENTER_DOOR
		HOTKEY_MASON_DOOR
		HOTKEY_TRAP_DOOR
		BUILDJOB_STOCKPILE_DELETE_CHILD
		STOCKPILE_ARMOR
		STOCKPILE_SETTINGS_DISABLE
		STORES_DUMP
		ORDERS_DYED_CLOTH
		ORDERS_ZONE_DRINKING
		D_DESIGNATE
		D_HAULING_STOP_LC_DIR
		D_BURROWS_DELETE
		D_NOTE_DELETE
		D_NOTE_ROUTE_DELETE
		D_BITEM_DUMP
		D_LOOK_DUMP
		ARENA_CREATURE_SIDE_UP
		ASSIGNTRADE_SORT
		DESIGNATE_DUMP
		DESIGNATE_DIG
		ITEM_DUMP
		D_MILITARY_DISBAND_SQUAD
		D_MILITARY_ALERTS_DELETE
		D_MILITARY_AMMUNITION_REMOVE_ITEM
		D_MILITARY_DELETE_UNIFORM
		STRING_A100
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		OPTION4
		CUSTOM_D
		WORLD_PARAM_DELETE
		LEGENDS_EXPORT_DETAILED_MAP
		A_COMBAT_DODGE
		A_STATUS_DESC
		A_SLEEP_DAWN
		A_INV_DROP
		A_END_TRAVEL
		SETUP_NOTES_DELETE_NOTE
		BUILDJOB_TARGET_RIGHT
		BUILDJOB_BED_DORMITORY
		BUILDJOB_FARM_WINTER
		BUILDJOB_RACKSTAND_KILL2
		HOTKEY_BUILDING_DOOR
		HOTKEY_BUILDING_CONSTRUCTION_STAIR_DOWN
		HOTKEY_BUILDING_WORKSHOP_DYER
		BUILDING_ORIENT_RIGHT
		BUILDING_ADVANCE_STAGE
		BUILDING_TRIGGER_MAX_SIZE_DOWN
		BUILDING_TRACK_STOP_DUMP
		HOTKEY_GLASS_DOOR
		HOTKEY_CARPENTER_DOOR
		HOTKEY_MASON_DOOR
		HOTKEY_TRAP_DOOR
		BUILDJOB_STOCKPILE_DELETE_CHILD
		STOCKPILE_ARMOR
		STOCKPILE_SETTINGS_DISABLE
		STORES_DUMP
		ORDERS_DYED_CLOTH
		ORDERS_ZONE_DRINKING
		D_DESIGNATE
		D_HAULING_STOP_LC_DIR
		D_BURROWS_DELETE
		D_NOTE_DELETE
		D_NOTE_ROUTE_DELETE
		D_BITEM_DUMP
		D_LOOK_DUMP
		ARENA_CREATURE_SIDE_UP
		ASSIGNTRADE_SORT
		DESIGNATE_DUMP
		DESIGNATE_DIG
		ITEM_DUMP
		D_MILITARY_DISBAND_SQUAD
		D_MILITARY_ALERTS_DELETE
		D_MILITARY_AMMUNITION_REMOVE_ITEM
		D_MILITARY_DELETE_UNIFORM
		STRING_A100
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_DOWN
		CURSOR_DOWN
		A_MOVE_S
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		OPTION4
		CUSTOM_D
		WORLD_PARAM_DELETE
		LEGENDS_EXPORT_DETAILED_MAP
		A_COMBAT_DODGE
		A_STATUS_DESC
		A_SLEEP_DAWN
		A_INV_DROP
		A_END_TRAVEL
		SETUP_NOTES_DELETE_NOTE
		BUILDJOB_TARGET_RIGHT
		BUILDJOB_BED_DORMITORY
		BUILDJOB_FARM_WINTER
		BUILDJOB_RACKSTAND_KILL2
		HOTKEY_BUILDING_DOOR
		HOTKEY_BUILDING_CONSTRUCTION_STAIR_DOWN
		HOTKEY_BUILDING_WORKSHOP_DYER
		BUILDING_ORIENT_RIGHT
		BUILDING_ADVANCE_STAGE
		BUILDING_TRIGGER_MAX_SIZE_DOWN
		BUILDING_TRACK_STOP_DUMP
		HOTKEY_GLASS_DOOR
		HOTKEY_CARPENTER_DOOR
		HOTKEY_MASON_DOOR
		HOTKEY_TRAP_DOOR
		BUILDJOB_STOCKPILE_DELETE_CHILD
		STOCKPILE_ARMOR
		STOCKPILE_SETTINGS_DISABLE
		STORES_DUMP
		ORDERS_DYED_CLOTH
		ORDERS_ZONE_DRINKING
		D_DESIGNATE
		D_HAULING_STOP_LC_DIR
		D_BURROWS_DELETE
		D_NOTE_DELETE
		D_NOTE_ROUTE_DELETE
		D_BITEM_DUMP
		D_LOOK_DUMP
		ARENA_CREATURE_SIDE_UP
		ASSIGNTRADE_SORT
		DESIGNATE_DUMP
		DESIGNATE_DIG
		ITEM_DUMP
		D_MILITARY_DISBAND_SQUAD
		D_MILITARY_ALERTS_DELETE
		D_MILITARY_AMMUNITION_REMOVE_ITEM
		D_MILITARY_DELETE_UNIFORM
		STRING_A100
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_LEFT
		CURSOR_LEFT
		WORLD_PARAM_DECREASE
		A_MOVE_W
	End of group
		STANDARDSCROLL_RIGHT
		CURSOR_RIGHT
		WORLD_PARAM_INCREASE
		A_MOVE_E
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		SELECT
		CLOSE_MEGA_ANNOUNCEMENT
		WORLD_PARAM_ENTER_VALUE
		SETUPGAME_SAVE_PROFILE_GO
		D_BURROWS_DEFINE
		D_MILITARY_ALERTS_SET
	End of group
		CUSTOM_CTRL_R
	End of group
End of macro
